### ISSUE TITLE
Adding Pumped Hydro Energy Storage in matpower

### ISSUE THREAD

**Issue by allrashdi10** [MATPOWER/matpower#102]
Hello.

I'm building a optimal power system and then I'll add a PHS on it and it will be consider as storage sometimes and as generation sometimes else. Now I want to know the way to add that in MATPOWER code, could I consider it generation data or in the load of bus data?

**Comment by rdzman** [comment]
Either one could be valid depending what you are trying to do.

If simply specifying the active and reactive power dispatch of the PHS as an input is adequate, then using the `PD` and `QD` columns of the `bus` matrix is perfectly fine.

If you want the OPF to dispatch the unit based on some cost function, then you will need to model it as a generator with positive `PMAX` and negative `PMIN`. With this model the reactive power will be dispatchable as well between `QMIN` and `QMAX`.
