### ISSUE TITLE
DC Tie Support in AC PF

### ISSUE THREAD

**Issue by gridxt** [MATPOWER/matpower#112]
Do you have any plan to add support for DC lines in the AC power flow? Thanks.

**Comment by rdzman** [comment]
There is a very basic model of a DC line already implemented, but we do plan to include better models in an upcoming version. Have a look at Section 7.6.3 in the [MATPOWER User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf) for a description of the current model. While it is implemented as an OPF extension, it does work for AC power flow as well.
