### ISSUE TITLE
Bug: runcpf with full trace and qlims

### ISSUE THREAD

**Issue by felnix96** [MATPOWER/matpower#12]
Here's what i stumbled on: 
When a gen exceeds his Qlim in the **first** iteration, a rollback is initiated and during this rollback the target Lambda (which is Zero in FULL trace mode) triggers the target lamda zero Event.
=> cpf terminates to early

**Comment by rdzman** [comment]
Thanks for reporting this. Do you have a short script that will reproduce this situation (preferably using one of MATPOWER's included cases)?
