### ISSUE TITLE
OPF (and PF) crash in ext2int() when all buses are isolated

### ISSUE THREAD

**Issue by SNPerkin** [MATPOWER/matpower#13]
**mpver:** 
MATPOWER               Version 6.0        16-Dec-2016
I believe this crash will also occur in the present github version of matpower.

**MWE:**
mpc = loadcase('case30');
mpc.bus(:,2) = 4;
runpf(mpc); %alternatively runopf(mpc) will result in the same crash

**Bug:**
Matpower does not presently handle cases in which all buses are set to isloated (mpc.bus(:,BUS_TYPE) = 4), causing ext2int() to crash with the following error report:

Error using sparse
Sparse matrix sizes must be non-negative integers less than MAXSIZE as defined by COMPUTER.  Use HELP COMPUTER for more details.

Error in ext2int (line 169)
            o.bus.e2i = sparse(max(o.bus.i2e), 1);

**Expected outcome:**
- text to screen stating, "powerflow not valid - all buses in casefile are isolated"
- mpc.success = 0
- does not cause matlab to stop the active script or to enter debugging mode

**Justification for bug fix:**
It is possible that any user who is simulating cascading faults or blackouts may arrive at such a case. Given that it is valid input (within the rules of matpower) to have all buses with type = 4, the code should therefore handle this case without requiring the user to manually catch/treat the case prior to running a PF/OPF.

**Comment by rdzman** [comment]
@SNPerkin Thanks for reporting this bug. Should be fixed now.
