### ISSUE TITLE
Negative Reserve

### ISSUE THREAD

**Issue by ragt2312** [MATPOWER/matpower#130]
It is not an issue, I just want to run a unit commitment problem with a fixed reserve requirement, but I want to know if there is a way to set a fixed negative (down) reserve requirement?. I see in the manual that the requirement specified in the manual is only for positive (up) reserve.

**Comment by rdzman** [comment]
Unfortunately, there is not a way to set a fixed requirement on down reserves in the current implementation. That is essentially a different service and would requires its own optimization variables, costs, and constraints.
