### ISSUE TITLE
Finding Shift Factor after applying contingencies

### ISSUE THREAD

**Issue by thomsonian2023** [MATPOWER/matpower#132]
Is it possible to calculate shift factor from PSSE RAW file using Matpower after applying a list of contingencies i.e. monitored lines which can potentially go on outage?

**Comment by rdzman** [comment]
Once you convert the RAW file to MATPOWER format using `psse2mpc()` you can compute line outage distribution factors using [`makeLODF()`](https://matpower.org/docs/ref/matpower7.1/lib/makeLODF.html) (also described in Section 4.5 in the [User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf)). Is that what you want?

**Comment by thomsonian2023** [comment]
It's not LODF calculation.

There is base RAW file and it comes with a list of contingencies. i.e. list of lines which could potentially go out but are still in service in the RAW file.

Since, this is a list of hypothetical outages, so they are not represented in RAW file. Hence, RAW file needs this additional outage information before calculating new shift factor accounting for list of contingencies.

**Comment by thomsonian2023** [comment]
That will be an additional file probably in a csv format.
