### ISSUE TITLE
300 bus system makeSbus fail

### ISSUE THREAD

**Issue by tyua321** [MATPOWER/matpower#135]
A simple example on case300
```
mpc0=loadcase('case300');
mpopt = mpoption( 'verbose', 0, 'out.all', 0);
result=runpf(mpc0,mpopt);
sbus = makeSbus(result.baseMVA, result.bus, result.gen);
```
The result is:
```
错误使用 sparse
索引超出数组范围。

出错 makeSbus (line 61)
    Cg = sparse(gbus, (1:ngon)', 1, nb, ngon);  %% connection matrix
```
Sorry my matlab system is in Chinese, it says the index is out of the range.

However it is good when I run it on other small grid like 14,30 bus system.

Can you help me with it?

**Comment by rdzman** [comment]
This is because `makeSbus()` expects inputs that have been converted to internal (consecutive) bus numbers via `ext2int()`.

So you can do ...
```
result_int = ext2int(result);
sbus = makeSbus(result_int.baseMVA, result_int.bus, result_int.gen);
```

The `ext2int()` function also removes off-line equipment, so the resulting `sbus` vector will correspond to on-line buses only.
