### ISSUE TITLE
Derivation of HVDC Qlim 

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#147]
Hi Dr. Zimmerman,

Is it possible to know how you derived this function, i.e "psse_convert_hvdc_Qlims"? (such as a document for explanation)
![image](https://user-images.githubusercontent.com/111019734/186716200-37585f22-052b-4e27-9417-3d8faa66b8d9.png)
Thanks a lot.

Best,
Yanda

**Comment by rdzman** [comment]
I'm afraid I don't have anything more than what is included in that comments, with a reference to Kimbark's book. I'm assuming these comments were written by the original author, Yujia Zhu, who was a student at Arizona State University at the time.

**Comment by yanda1234** [comment]
> I'm afraid I don't have anything more than what is included in that comments, with a reference to Kimbark's book. I'm assuming these comments were written by the original author, Yujia Zhu, who was a student at Arizona State University at the time.

I see. Thanks, Dr. Zimmerman.
