### ISSUE TITLE
delta-star transformation

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#148]
Hi Dr.Zimmerman,

I just notice matpower implements delta-star transformation in this way. 
![image](https://user-images.githubusercontent.com/111019734/187311684-1ded6f7b-2ee1-41ed-98ec-fdfe4ae174ee.png)
The correct way should be as below, right?
![image](https://user-images.githubusercontent.com/111019734/187311927-f26a0bee-a6e1-4e79-90bd-ba59a152875f.png)

Best,
Yanda

**Comment by rdzman** [comment]
It looks to me like this code is based on Eqs. 2 from [this article](https://www.yumpu.com/en/document/view/10534310/modeling-of-three-winding-voltage-regulating-transformers) and is correct.

However, if you still have doubts after looking at that, my only suggestion would be to attempt to contact the original author of the code, Yujia Zhu, to get more insight or confirmation. Let me know if you feel that's necessary and I'll see what I can do.

**Comment by yanda1234** [comment]
I see your point. Thanks for your clarification, Dr. Zimmerman!
