### ISSUE TITLE
DCOPF didn't converge

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#151]
I built a power flow case based on a promod file data, but while running DCOPF onto it, I encountered error as below.
What made me confused was I have already relaxed branches' constraints and the max capacity is enough to satisfy system load.
What might be the reason for the problem? Kindly advise. Many thanks.

>> a=rundcopf('no_island_major_study_system.m');

MATPOWER Version 7.0, 20-Jun-2019 -- DC Optimal Power Flow
Error: basis matrix is singular to working precision (cond = 8.84e+18)
glp_simplex: unable to recover undefined or non-optimal solution

>>>>>  Did NOT converge (7.65 seconds)  <<<<<

![image](https://user-images.githubusercontent.com/111019734/198070014-157399ab-9d78-4c5a-b46e-8eab6ccf1697.png)
![image](https://user-images.githubusercontent.com/111019734/198070351-e9577689-88c0-42df-b09f-a2fe423fa15b.png)
![image](https://user-images.githubusercontent.com/111019734/198070491-3c4cf9f2-5bb6-45ac-b01b-f18ddb579b27.png)
![image](https://user-images.githubusercontent.com/111019734/198070626-6249e6e1-622f-4859-bd01-dcb65248b09a.png)

**Comment by rdzman** [comment]
Have you checked to make sure there are no branches with zero or near-zero reactance?

Which solver are you using?

I don't recognize the error message or the function that is throwing the error (`glp_simplex`).

**Comment by yanda1234** [comment]
You are right. The problem is in the branch impedance. Some data are weird. Thanks, Dr. Zimmerman.
