### ISSUE TITLE
is it possible to apply constraint for the sum of multiple branches' total flow

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#156]
Hi Dr. Zimmerman,

I am curious if there is an easy way to apply constraint for the sum of multiple branches' total flow, instead of just one branch's flow.

Best,
Yanda

**Comment by rdzman** [comment]
For the DC OPF case, see Section 7.6.2 in the [User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf
).

**Comment by yanda1234** [comment]
Thanks, Dr. Zimmerman. I noticed the t_case30_userfcns.m etc were not included in matpower 7.0. And some other interesting functions or cases were also deleted. Could you please explain a little bit why you removed them?

**Comment by rdzman** [comment]
It was not removed. You can find it in `lib/t` in versions [7.0](https://github.com/MATPOWER/matpower/blob/7.0/lib/t/t_case30_userfcns.m) and [7.1](https://github.com/MATPOWER/matpower/blob/7.1/lib/t/t_case30_userfcns.m) and the current [master branch](https://github.com/MATPOWER/matpower/blob/master/lib/t/t_case30_userfcns.m).

**Comment by yanda1234** [comment]
I see. The letter 't' here means "test", right?

**Comment by rdzman** [comment]
Yes, `t` is the test directory.
