### ISSUE TITLE
PTDF larger than 1

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#157]
Hi Dr. Zimmerman,

While running makePTDF, I found sometime the PTDF values are even larger than 1, which is weird. Do you know why this can happen? Due to negative impedance or phase shifter transformers?

Best,
Yanda

**Comment by rdzman** [comment]
I'm afraid I don't have a good answer to that question. My hunch is that it could be caused by a negative impedance, but I'm really not sure.

**Comment by yanda1234** [comment]
Your intuition is right, Dr. Zimmerman.
