### ISSUE TITLE
How to get the frequency of the Optimal powerflow?

### ISSUE THREAD

**Issue by irfanbabar42** [MATPOWER/matpower#165]
Hi,
I am trying to get the frequency of the system. How I can get the frequency ? I need want to track the frequency behavior with the change in load and other bus  values.
Thanks

**Comment by rdzman** [comment]
For steady-state analysis, such as power flow and optimal power flow, the frequency is assumed to be fixed at the nominal frequency.

**Comment by rdzman** [comment]
Frequency is considered variable when studying transient phenomenon ... like you say, thinks like sudden changes in load. MATPOWER assumes we are dealing with steady state. To study transients, you'll need a different tool.

**Comment by irfanbabar42** [comment]
@rdzman Thank you so much. I really appreciate your help.
