### ISSUE TITLE
Put default tap ratio (=1) to documentation

### ISSUE THREAD

**Issue by 8986ca6c** [MATPOWER/matpower#17]
As one can see in makeYbus.m there is a default tap ratio ![equation](http://www.sciweavers.org/tex2img.php?eq=%5Ctau%3D1&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0), used when its value is 0. This appears quite often in case5, case9, case14... (I suppose there are even more examples, but I think three are enough). Whithout knowing about the default bahavior, these cases seem to be very weird, as ![equation](http://www.sciweavers.org/tex2img.php?eq=%5Cfrac%7B%7CV_f%7C%7D%7B%7CV_t%7C%7D%20%3D0&bc=White&fc=Black&im=jpg&fs=12&ff=arev&edit=0) in many branches (assuming r=x=b=0 for cases of simplicity to show this weird ratio).

There is no hint on this default tap ratio in the documentation. This led me to spend (waste?) time on understanding, why the above mentioned cases actually work. 

I'd be thankful if you could add this information to the ducumentation, e.g. in Table B-3: Branch Data. Think this could help others too. Thank you.

**Comment by rdzman** [comment]
You are right. The only indication was in `caseformat` where it says _( = 0 for lines )_.

Sorry for the confusion. I have added clarification to both Table B-3 and the description in `caseformat`, as well as adding a footnote in Section 3.2.

_Note the manual updates currently are only in the LaTeX source, not the PDF. So I've attached an updated PDF below._

- [MATPOWER-manual.pdf](https://github.com/MATPOWER/matpower/files/1142006/MATPOWER-manual.pdf)
