### ISSUE TITLE
Error while using psse2mpc

### ISSUE THREAD

**Issue by DiegoCanas** [MATPOWER/matpower#170]
Hello, I was trying to import a .raw with psse2mpc and I get an error that I do't understand, can someone help me? Thank you.

My code:
![image](https://user-images.githubusercontent.com/90197134/223376869-28760831-8b66-4ce3-94a1-e62c1cd4d315.png)

The error:
![image](https://user-images.githubusercontent.com/90197134/223376904-517dcc20-24d7-4d36-9c98-37583ce5e6ed.png)

**Comment by rdzman** [comment]
Are you certain 33 is the correct RAW file version? Have you tried others?

Any chance you could share the input file so I can replicate the issue and look into it?
