### ISSUE TITLE
24 hours load data needed for IEEE 33 or 69 bus system

### ISSUE THREAD

**Issue by mj00712** [MATPOWER/matpower#172]
Hi. I hope you are doing well. Kindly provide 24-hour load data on all buses for the IEEE 33 or 69 bus distribution network. I will be very grateful to you.

**Comment by rdzman** [comment]
Do you know if this data exists? If so, and you can provide a source, I'd be happy to include it in MATPOWER.

However, if you are asking for us to create data for these networks, I'm afraid that is out of the scope of the MATPOWER project. Plus, if we are talking about creating data, I suspect that you, being closest to the intended use of the data, are probably better positioned than anyone to create data with the assumptions relevant for your project.

**Comment by mj00712** [comment]
I have data for the CIGRE network, the data they have used in the paper is not built using matpower. Kindly can you convert this data to matpower format. Also, I have 24 hours load data that is given in this paper [https://www.mdpi.com/1996-1073/15/10/3701](url). The data that they are using is given below for which Ploss and Qloss are 19.9771 kW, and 19.8932 kVar, respectively. This data is static data but it had to be first converted to matpower format to verify the results and then using the reference paper we can perform 24 hours load flow for that case. `% %         |Bus | Type | Vsp | theta | PGi |   QGi | PLi | QLi |  Qmin | Qmax |
busdat14 = [1     3    1.03     0       0       0    13.89   3.29    0       0;
            2     1    1.03     0       0       0    0.00    0.00    0       0;
            3     3    1.03     0       0.00447 0    0.35    0.15    0       0;
            4     3    1.03     0       0.00447 0    0.30    0.08    0       0;
            5     3    1.03     0       0.6380  0    0.51    0.13    0       0;
            6     3    1.03     0       0.0067  0    0.38    0.103  -6      30;
            7     3    1.03     0       0.450   0    0.05    0.03    0       0;
            8     3    1.03     0       0.0067  0    0.41    0.10    0      24;
            9     3    1.03     0       0.3167  0    0.40    0.25   -6      44;
            10    3    1.03     0       0.2237  0    0.38    0.11   -6      24;
            11    3    1.03     0       0.0022  0    0.23    0.06    0       0;
            12    3    1.03     0       0       0    14.01   3.29    0       0;
            13    3    1.03     0       0       0    0.02    0.01    0       0;
            14    3    1.03     0       0       0    0.38    0.18   -6      24;];`
`% Line Data for IEEE 14 bus system
%         From to    R          X        B/2      T    
linedat14=[1   2    0.353      0.505  0.00053    1;
           2   3    0.554      0.791  0.00840     1;
           3   4    0.076      0.109  0.00116     1;
           4   5    0.070      0.100  0.00106     1;
           5   6    0.193      0.276  0.00293     1;
           6   7    0.030      0.043  0.00046     1;
           7   8    0.209      0.299  0.00317     1;
           8   9    0.040      0.057  0.00061     0.932;
           9  10    0.096      0.138  0.00146     0.978;
          10  11    0.041      0.059  0.00063     1;
          11   4    0.061      0.088  0.00093     0.969;
           3   8    0.163      0.233  0.00247     1;
          12  13    0.623      0.447  0.00062     1;
          13  14    0.381      0.274  0.00038     1;
          14   8    0.255      0.183  0.00025     1];`

**Comment by mj00712** [comment]
[Linedata](https://snipboard.io/I13OqQ.jpg)
[Busdata](https://snipboard.io/V2BHWd.jpg)
Linedata and Busdata are given in these images.
