### ISSUE TITLE
Add user-defined constraints into Matpower via python

### ISSUE THREAD

**Issue by zhiyuliao** [MATPOWER/matpower#174]
I want to insert various new constraints in Matpower via python. Is it available? Because I did not find much information on the Internet. Besides, I also want to alter the objective function in Matpower. My friend suggests me add constraints and an objective function in the Yalmip. After that, input all results into the Matpower. Is there others methods to achieve？

**Comment by rdzman** [comment]
MATPOWER does not use YALMIP, so I don't think that approach will work. Some types of constraints can be specified completely in the input data, which I suppose could be generated from Python, but I'll need a bit more information on what you're trying to accomplish?

- How are Python and MATPOWER related in your scenario? Are you using Python just to generate input files for MATPOWER? Calling MATPOWER directly from Python? If so, how?
- What are the user-defined constraints? Are they linear? Non-linear? Functions of what variables?
- What is the objective you would like to use? Function of what variables?
