### ISSUE TITLE
How to add linear constraints in the standard OPF?

### ISSUE THREAD

**Issue by YHLjun** [MATPOWER/matpower#176]
Hi,

I want to add additional constraints for Pg to original OPF. I use "add_constraints('name', A, l, u, varset)" to add. but the matlab always said there is no add_constraints function..... So how to add it? My version is is 7.1.

It would be appreciated thta a simple example can be provided, such as 80MW>=3*Pg+2MW>=15....

Kind Regards
YHL

**Comment by rdzman** [comment]
See Section 6.3 and Chapter 7 of the [MATPOWER User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf). To use the [`add_lin_constraint()`](https://github.com/MATPOWER/mp-opt-model/blob/master/lib/%40opt_model/add_lin_constraint.m) method of the [`opt_model`](https://github.com/MATPOWER/mp-opt-model/blob/master/lib/%40opt_model/opt_model.m) (`om`) object, you would need to use the callback function approach. The direct method, where you specify `A`, `l`, and `u` directly as additional fields in `mpc` is often much simpler. The only thing is that the columns of `A` must correspond to the full set of optimization variables. By default, that is `[Va; Vm; Pg; Qg]`, that is bus voltage angles and magnitudes, followed by generator active and reactive injections.

FWIW, your example looks like simple bounds on the active generation, which you can accomplish with `gen(:, PMIN)` and `gen(:, PMAX)`.
