### ISSUE TITLE
How to get P and Q losses in branch directly from the result.branch

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#177]
When I run the power flow I can see the active and reactive power losses directly printed out. But If I want to get these branch losses how can I get it. I have tried to use this code to get it but the results are inaccurate.
result = runpf(mpc, options);
P_from = result.branch(:,14);
Q_from = result.branch(:,15);
P_to = result.branch(:,16);
Q_to = result.branch(:,17);

% Calculate active and reactive power losses in branches
P_losses = P_from +P_to; % Active power losses in branches
Q_losses = Q_from + Q_to; % Reactive power losses in branches

but it does not work. It works if there is no active power injection at buses but if there is additional power injection how to calculate losses properly for each branch.

**Comment by rdzman** [comment]
Summing the power injections at the ends of the branch will give you total losses in the branch. Sometimes, what is desired is only the series losses, not including the line charging component. This is what is printed in the branch section of the console output.

In any case, you can use [`get_losses()`](https://github.com/MATPOWER/matpower/blob/master/lib/get_losses.m) to easily compute each component of the branch losses.
