### ISSUE TITLE
convex or non-convex

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#179]
Hi Dr. Zimmerman,

I am curious if all units' gencost c2 column are zero and only c1 and c0 have non-zero values, is the DCOPF convex or non-convex? Is there any other non-linear constraint?
I ask this is because I found the DCOPF can converge to different optimal points which have different function values, but I cannot understand why it is non-convex. (I used different order to eliminate same list of buses in Kron reduction and get two same MPC files.)
Kindly let me know your thoughts. Many thanks in advance.

Best,
Yanda

**Comment by rdzman** [comment]
> I am curious if all units' gencost c2 column are zero and only c1 and c0 have non-zero values, is the DCOPF convex or non-convex? Is there any other non-linear constraint?

It is a linear program (LP), in other words, all linear costs and all linear constraints, and therefore it is convex.

> I ask this is because I found the DCOPF can converge to different optimal points which have different function values, but I cannot understand why it is non-convex.

So, are you saying you have a single DC OPF problem that you can solve twice and get two different solutions with different objective function values? This should not happen. An LP may have multiple optimal solutions, but they should all have the same objective function value. What are you changing between the two solutions? Starting point? Solver algorithm? Can you provide a reproducible example for me to look at?

> (I used different order to eliminate same list of buses in Kron reduction and get two same MPC files.)

I'm not sure I understand where you are encountering the problematic DCOPF mentioned above? Is it on the final reduced system, or during the Kron reduction process?
