### ISSUE TITLE
DCOPF doesn't converge due to PMIN of some units

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#183]
Hi Dr. Zimmerman,

I encountered a problem while using matpower. DCOPF cannot converge on one case, **even after setting branch capacities to be all 0 (infinite)**.
**Then I used toggle_softlims to investigate the reason and found it was caused by several units' Pmin are too large.**
I compared all units' Pmin and ensured their sum is smaller than total amount of load. Besides, I also checked the "ratio" and "angle" columns of branch are all zero. I am curious which constraints might lead to this issue.

Kindly advise.

Best,
Yanda

**Comment by rdzman** [comment]
Hmmm ... that does sound strange. You're saying that the **only** soft-limits violations you see are a few PMIN limits? And some of the other generators are presumably above their PMIN? If so, is this a case you could share with me (via direct e-mail is fine if you don't want to post it publicly here)?
