### ISSUE TITLE
Meaning of PG and QG variables

### ISSUE THREAD

**Issue by mzgubic** [MATPOWER/matpower#186]
Hello, apologies for a very basic question. The [manual](https://matpower.org/docs/MATPOWER-manual.pdf) says that `PG` is the real power output of a generator and `QG` is the reactive power output. My understanding is that real power output of the generator can vary between `PMIN` and `PMAX` and is an output of solving OPF. So I'm assuming that the `PG` and `QG` values refer to some sort of (prior?) operating point?

**Comment by rdzman** [comment]
`PG` and `QG` serve as both inputs and outputs (solution values).

As inputs, for example `PG` specifies the generator setpoint for power flow, and for some OPF solvers they can specify the initial values of the corresponding optimization variables.

**Comment by mzgubic** [comment]
Thank you!
