### ISSUE TITLE
Newton's method did not converge in 10 iterations. PF failed

### ISSUE THREAD

**Issue by Cihagnir** [MATPOWER/matpower#188]
function mpc = Input_data 
%% MATPOWER Format : V1
mpc.version = '2';

%%---- Simulation Data ----%% 
%% MVA Base 
mpc.baseMVA = 100;

%% Bus Data 

mpc.bus = [
%	bus_i	type   Pd	  Qd	Gs	  Bs	area	Vm	    Va	    baseKV	zone	Vmax	Vmin
	  1	     2	   0	  0	    0	  0	     1	    1.04	 0	    13.2	    1	    1.1	    0.9;
	  2	     1	   0	  0	    0	  0	     1	    1.04	 0	    220	    1	    1.1	    0.9;
	  3	     1	   60	  30	0	  0	     1	    1.04	 0	    220	    1	    1.1	    0.9;
	  4	     1	   50	  20	0	  0	     1	    1.04	 0	    220	    1  	    1.1	    0.9;
	  5	     1	   40	  30	0	  0	     1	    1.04	 0	    220	    1	    1.1	    0.9;
	  6	     1	   20	  10	0	  0	     1	    1.04	 0	    220	    1	    1.1	    0.9;
	  7	     1	   45	  30	0	  0	     1	    1.04	 0	    220	    1	    1.1	    0.9;
	  8	     1	   60     20	0	  0	     1	    1.04	 0	    220	    1	    1.1	    0.9;
	  9	     3	   0	  0		0	  0	     1	    1.04	 0	    15.4	1	    1.1	    0.9;    
];

%% Line Data 
mpc.branch = [

%	fbus	tbus	r	        x	    b	    rateA	rateB	rateC	ratio	angle	status	angmin	angmax  
    1       2       0           0.41    0       400	    400	    400     0	    0   	1	    -360	360;
    2       3       0.0096      0.072   0       400	    400	    400	    0	    0   	1	    -360	360;
    3       4       0.0128      0.096   0       400	    400	    400	    0	    0	    1	    -360	360;
    4       5       0.0128      0.096   0       400	    400	    400	    0	    0   	1	    -360	360;
    5       6       0.0112      0.084   0       400	    400	    400     0       0       1       -360	360;
    6       7       0.0256      0.192   0       400	    400	    400     0       0       1       -360	360;
    7       8       0.0192      0.144   0       400	    400	    400	    0	    0	    1	    -360	360;
    8       9       0           0.64    0       400	    400	    400	    0	    0   	1	    -360	360;
];

%% Generator Data 

mpc.gen = [

%	bus Pg	    Qg	    Qmax	Qmin	Vg	    mBase	status	Pmax	Pmin	Pc1	Pc2	Qc1min	Qc1max	Qc2min	Qc2max	ramp_agc	ramp_10	ramp_30	ramp_q	apf  
    1	200	    223.60	300	    -300	1.04	100	    1	    300	    10	    0	0	0	    0	    0	    0	    0	         0	    0	    0	    0;
    9	200	    346.41	300	    -300	1.04	100	    1	    300	    10	    0	0	0	    0	    0	    0	    0	         0	    0	    0	    0;
];
%% Gen Cost Data

mpc.gencost = [
%   model   startup     ShutDown    NCost   COST    PW_LINEAR   POLYNOMIAL
	2	    1500	    0	        3	    0.11	    5	    150;
	2	    2000	    0	        3	    0.085	    1.2	    600;
];

---------------------------------------------------------------------------------------------------------------------------------------

That is my input data structure. 

And that is my basic code to use to solve the case on the "Newton Power Flow" equation.
################

mpc = loadcase('Input_data');

case_info(mpc); 

runpf(mpc);

################

However, I keep getting that error. 

####################
MATPOWER Version 8.0b1, 30-May-2023
Power Flow -- AC-polar-power formulation

Newton's method did not converge in 10 iterations.
PF failed

>>>>>  Did NOT converge (0.04 seconds)  <<<<<

####################

I already tried to increase my iteration count however it's not chang anything . I will be glad to help.

**Comment by rdzman** [comment]
See [FAQ #5](https://matpower.org/doc/faq/#pfconvergence) for some tips on sorting out the cause.
