### ISSUE TITLE
How to add storage + generation in casefile.

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#189]
If I have a PV system of 30kw and storage of 20kwh for a bus, how can I add that for example in case 33 bus or generator data? Is there any example casefile for such case?

Regards,
Akhtar

**Comment by rdzman** [comment]
For what problem? Power flow? optimal power flow? Unit-commitment?

**Comment by akhtar3100** [comment]
For powerflow and optimal powerflow

**Comment by rdzman** [comment]
For power flow and optimal power flow, both can be modeled as a generator. Simply set the parameters and costs appropriately for the units (i.e. cost of solar is probably zero, PMIN of storage is negative, etc).

**Comment by akhtar3100** [comment]
ok. Thanks
