### ISSUE TITLE
mpoption problem

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#190]
Hi Dr. Zimmerman,

While running **mpoption('gurobi.method',1)**,  I got:
**error using mpoption
mpoption: 'gurobi' is not a valid option name.**
Does that mean gurobi solver is not existed?
Kindly advise.

Best,
Yanda

**Comment by rdzman** [comment]
That is correct. You can also run `mpver` and see what the output says next to Gurobi.

**Comment by yanda1234** [comment]
Thanks a lot, Dr. Zimmerman!
