### ISSUE TITLE
after installing gurobi, how to let matpower know it?

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#191]
Hi Dr. Zimmerman,

Sorry to disturb you before holiday. For some reason, I need to install gurobi again, but after that, I found matpower cannot recognize it.
I believe gurobi is installed and the link between matlab and gurobi is also installed, since I tested a gurobi case from matlab.
However, the problem is matpower cannot call gurobi. I tried mpoption('gurobi.method',1) and mpver. And the first command brought back me an error message, while the second one got me gurobi is not installed. Do you know how to fix it? Kindly advise.

Many thanks.

Best,
Yanda

**Comment by rdzman** [comment]
MATPOWER checks once for the presence of external solvers, then caches the result to make future checks faster. You can clear that cache by doing ...
```
have_feature('all', 'clear_cache')
```
... or simply restart you MATLAB session. Then it should find it.

**Comment by yanda1234** [comment]
Hi Dr. Zimmerman,

This function doesn't work for me. 
![image](https://github.com/MATPOWER/matpower/assets/111019734/3f71811e-8916-43b2-adee-c476e36d1e7d)
![image](https://github.com/MATPOWER/matpower/assets/111019734/7f3b47c6-ffa7-4f2f-b5b5-829ed4f06e6c)
![image](https://github.com/MATPOWER/matpower/assets/111019734/ed527277-2476-42ab-b640-6d40bb50fd07)

And I restarted matlab, but matpower still cannot recognize gurobi. Do you have any thoughts? 


Best,
Yanda

**Comment by rdzman** [comment]
What version of MATPOWER are you using?
And what is the output when you type: `which gurobi` ?

**Comment by yanda1234** [comment]
![image](https://github.com/MATPOWER/matpower/assets/111019734/2a6618ea-5a89-4bf0-bdf0-d0374c78cb8e)
Matpower version is 7.0

**Comment by rdzman** [comment]
The fact that it can't find `have_feature()` means that either you are using a version of MATPOWER before 7.1, or it is not properly installed.

But if Gurobi is in the MATLAB path after restart, it should find it anyway.

**Comment by yanda1234** [comment]
Actually, I need to type gurobi_setup each time right now. Do you mean that I can either use matpower 7.1 or ensure gurobi is in matlab path?


Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rdzman** [comment]
Hmm, I'm not aware of any issues with MATPOWER 7.0 and Gurobi 9.5.2.
What does `exist('gurobi', 'file')` return?
And what happens if you try the following?
```
model = struct( ...
    'A', sparse(1), ...
    'rhs', 1, ...
    'sense', '=', ...
    'vtype', 'C', ...
    'obj', 1, ...
    'modelsense', 'min' ...
);
params = struct( ...
    'outputflag', 0 ...
);
result = gurobi(model, params);
```

**Comment by rdzman** [comment]
Yes, Gurobi must be in the MATLAB path for MATPOWER to find it ... regardless of the version of MATPOWER.

**Comment by yanda1234** [comment]
If I add path each time, instead of saving there permanently, is it ok?

**Comment by yanda1234** [comment]
![image](https://github.com/MATPOWER/matpower/assets/111019734/f20ffeae-7758-4641-807a-9a8b91edc1d8)

**Comment by rdzman** [comment]
As long as you add it to your path **before** MATPOWER tries to check for its availability you should be fine. If MATPOWER checks first, then it will not find it and will cache that result and not check again.

**Comment by yanda1234** [comment]
I see. Is there any problem for the model, params and result?

**Comment by rdzman** [comment]
No, I was just hoping it would produce an error that would help me figure out the problem. But you must have had Gurobi in your path that time, so no error.

**Comment by rdzman** [comment]
But it's not a bad idea to update to the latest MATPOWER.

**Comment by yanda1234** [comment]
Thanks, Dr. Zimmerman. Let me try to ask administrator save gurobi path permanently. If it still doesn’t work, I will update matpower to 7.1. Hopefully, it will be ok by then.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by yanda1234** [comment]
Hi Dr. Zimmerman,

After I cleared cache, the mpver works, which means matpower can recognize gurobi, right?
![image](https://github.com/MATPOWER/matpower/assets/111019734/8e339215-e92b-4c36-a0de-eeb933660408)
However, mpoption still doesn't work. Do you have any thoughts?
![image](https://github.com/MATPOWER/matpower/assets/111019734/85172053-06e1-4f2f-9566-b0e845fc6b98)


Best,
Yanda

**Comment by rdzman** [comment]
I don't understand how that can happen. Can you start a new MATLAB session, make sure Gurobi is in the path **before** using any MATPOWER commands, then try `mpver` and `mpoption('gurobi.method', 1)`?

Both should work. If not, maybe something got corrupted with your MATPOWER install and you need to reinstall (or better yet, upgrade) MATPOWER.

**Comment by yanda1234** [comment]
It is interesting. It works this time, although I still don't know why... Thanks a lot.
