### ISSUE TITLE
what is OSQP

### ISSUE THREAD

**Issue by AboLregal** [MATPOWER/matpower#194]
![image](https://github.com/MATPOWER/matpower/assets/36906638/ef9a8e19-c994-4d07-98ad-d376487ee371)

Hello , when I do runpf or runopf even for saved cases , it give me this problem.
how to solve it?

**Comment by rdzman** [comment]
[OSQP](https://osqp.org) is an optional solver for LP/QP problems, and MATPOWER can use it to solve, for example, the DC OPF.

MATPOWER checks for installation of optional solvers, including OSQP. In your case, it looks like MATLAB finds a file or function named `osqp`, but it does not work as expected.

I suggest you either remove that file from the MATLAB path or re-install a working OSQP. You can see exactly where the problematic file is located by typing ...
```
which osqp
```
