### ISSUE TITLE
Q Loss does not making sense

### ISSUE THREAD

**Issue by AboLregal** [MATPOWER/matpower#195]
![image](https://github.com/MATPOWER/matpower/assets/36906638/d2ef28f1-dd85-4aaf-b69f-9e94c4638822)
hello , how can Q values make any sense?

by the way I have OSQP error

**Comment by rdzman** [comment]
There are two components to reactive "loss" in a line.
- The series or `I^2 * Z` losses _(displayed here)_.
- The reactive injections (negative "loss") from line charging capacitance _(not displayed here)_.

Together they should add up to the difference between the reactive flow at the two ends of the branch. You can get both components from [`get_losses()`](https://github.com/MATPOWER/matpower/blob/master/lib/get_losses.m).
