### ISSUE TITLE
How to perform powerflow with generators with specefic Pg and Qg

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#198]
I have noticed that when we runpf in matpower it only considers Pg of generators and Qg of generators is calculated, That is also what basic powerflow does. But is it possible to runpf with specefic values of generators Pg and Qg given, I want powerflow to consider generators active and reactive powers both and then run powerflow, how can I do that? I mean power flow should not find Q, it should use Qg given to find voltage magnitude, angles and power losses. I have seen matpower manual it says that I should use dispatchable load with negative values of load. If I do that do I need to make both active and reactive power negative or only active powers negative. If I runpf after making generators as dispatchable loads the behavior is not equivalent to generators, for example a feeder with only generators should have higher voltage at the end of the feeder. In dispatchable loads it is not the result, i get low voltage. Am I doing something wrong?

**Comment by rdzman** [comment]
For a power flow, if you want to specify both P and Q for a generator, rather than P and |V|, simply change the bus type _(`BUS_TYPE` column in the `bus` matrix)_ from 2 _(PV)_ to 1 _(PQ)_.

Dispatchable loads are only for the OPF.

**Comment by akhtar3100** [comment]
Ok. thanks for reply. In this case I will keep bus pd and qd as zero and generator pg and qg will be negative values, right?

**Comment by rdzman** [comment]
Generator QG can be positive or negative, but will scale with PD as it is dispatched, maintaining a constant power factor.
