### ISSUE TITLE
problem in opf and other questions

### ISSUE THREAD

**Issue by AboLregal** [MATPOWER/matpower#202]
I have a system that worked in runpf
![1](https://github.com/MATPOWER/matpower/assets/36906638/873a05f2-defa-47c1-a595-de66612e049f)

but when using runopf
![2](https://github.com/MATPOWER/matpower/assets/36906638/9428b233-3b8b-4c73-abb2-056aa635fe94)

also why Q loss is too high?
finally is the line input in data is presented as double circuit or single?

**Comment by rdzman** [comment]
I'm afraid I don't know why the OPF does not converge or why the Q losses are so high without seeing the details of the case.

And I'm not sure what you mean by your last question? You can include parallel circuits as separate branches or as a single equivalent branch, if that's what you are asking.

**Comment by AboLregal** [comment]
please take a look to my excell file
[my project](https://docs.google.com/spreadsheets/d/1ZxRjxkS2-I5ar4tmsCwWcx0Z0DS6QrXc/edit?usp=sharing&ouid=109801219847984151200&rtpof=true&sd=true)

**Comment by rdzman** [comment]
Could you please attach a single casefile that can run directly?

**Comment by AboLregal** [comment]
sure, thanks for help [Link](https://drive.google.com/file/d/1fkPVkM3kE7Qgs31I_2Pj2Nt7yboHcAxQ/view?usp=sharing)

**Comment by rdzman** [comment]
A few quick observations ...

- The upper bound on generator 1's active generation is lower than it's lower bound  (PMAX < PMIN), making the problem trivially infeasible.
- The voltages from the power flow are extremely low at some buses (<0.6pu), **far** below the VMIN value of 0.93. This indicates either a problem in the data, or a problem in the specified operating point.
- Many of the branches have what appear to be extremely large values (> 1pu) for the BR_B column. You may want to double-check them to make sure they are correct.

**Comment by AboLregal** [comment]
do you have suggestions to improve voltage perunit?

**Comment by rdzman** [comment]
I'm afraid that's outside the scope of this forum ... more of a general power systems design question, not specifically a MATPOWER issue.
