### ISSUE TITLE
Can I perform linearized distflow using matpower?

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#203]
Hi! I am working on problem where I want to use linearized distflow for votlage and active and reactive power calculations. Is there a way in matpower to perform the distflow? Is it possible to use calc_v_pq_sum and ignore quadratic losses there.

**Comment by rdzman** [comment]
I'm afraid you would have to implement your own.

I didn't write the `calc_v_pq_sum()` code, so I'm not really sure if that would offer a helpful starting point.

**Comment by akhtar3100** [comment]
ok. Thanks
