### ISSUE TITLE
CPF bug when cpf_corrector fails on first iteration

### ISSUE THREAD

**Issue by ElisNycander** [MATPOWER/matpower#21]
I have found a small bug in the CPF function. Suppose the base case power flow converges but the very first corrector step fails. Then the following happens

1. cpf loop sets cont_steps = 0 and terminates with break
2. callback function is called with k=0 and thus executes initialization instead of final callback loop
3. cpf_results is now missing the field V (and all other fields which are supposed to be set in final callback loop)
4. missing cpf_results.V causes error on line 634 in runcpf:
    n = size(cpf_results.V, 2);

So the reason for this error is that the first parameter taken by the callback functions has two different functions. It is both
1. An indicator what stage the cpf is in, i.e. initialization stage, continuation stage, or final stage
2. A counter for the number of iterations which has been run
So the possibility of being in the final stage (because the corrector did not converge) in the very first iteration creates problems. 

Working example code:
```
clear;
close all;
define_constants;

mpc = case4gs();

% base case, change bus 4 to PQ, change limits for generator at bus 1
mpc.bus(4,[BUS_TYPE PD QD]) = ...
   [1 -820 238.3673];
mpc.gen(1,GEN_STATUS) = 0;
mpc.gen(2,[QMAX PMAX]) = [1e9 500];

% target case, increase load at bus 3
mpc1 = mpc;
mpc2 = mpc;
mpc2.bus(3,[PD QD]) = 2*mpc.bus(3,[PD QD]);

mpopt = mpoption();
mpopt.cpf.enforce_q_lims = 1;

mpc3 = runcpf(mpc1,mpc2,mpopt);
````

**Comment by rdzman** [comment]
Just to clarify, PR #25 referenced this issue by mistake. It is unrelated.
