### ISSUE TITLE
how to define reactive power costs for generators in mpc file.

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#219]
How can i define the cost of reactive power in my mpc file. Is there any example for that? I want to add model=2 polynomial costs for reactive power.

**Comment by rdzman** [comment]
See the footnote in Table B-4 in the [MATPOWER User's Manual](https://matpower.org/docs/MATPOWER-manual-7.1.pdf).

For a case with _ng_ generators, you can add an additional _ng_ rows to to `gencost`. The first _ng_ rows will be costs on active power, the second set of _ng_ rows will be costs on reactive power, in exactly the same format.
