### ISSUE TITLE
Issue regarding Installation

### ISSUE THREAD

**Issue by viswanath1494** [MATPOWER/matpower#22]
I tried installing MATPOWER on my computer. After adding it to the path in MATLAB, I typed in test_matpower and I got this error. How do I resolve this issue?
![matpower error](https://user-images.githubusercontent.com/31635270/30039321-30d1537e-919d-11e7-8251-57eaa4e1a56a.JPG)

**Comment by rdzman** [comment]
What version of MATPOWER is this? And did you use the installation instructions for your version? _(The GitHub version uses different paths and includes an installer. See [Installation](https://github.com/MATPOWER/matpower/#installation))_.

If that isn't the issue, please run the failing tests individually and provide the output here.
`t_feval_w_path`
`t_load_case`

**Comment by rdzman** [comment]
Did you resolve this?

If we don't receive more info here in a few days, we will assume you were able to resolve the problem and will close this issue.

**Comment by viswanath1494** [comment]
It got resolved. Thank you
