### ISSUE TITLE
How can I perform load flow calculation without converting the values into per unit values in matpower

### ISSUE THREAD

**Issue by akhtar3100** [MATPOWER/matpower#220]
I have a casefile, in which I don't want to convert p,q load, generators and even branch impedances in to per unit value. But when I runpf I get convergence error. How can I do loadflow without have to convert the values into per unit values.

**Comment by rdzman** [comment]
I have not tried this, but it should work if you set baseMVA to 1 and be sure to specify all of the power, voltage and impedance parameters in consistent units (e.g. MW, kV, Ohms).
