### ISSUE TITLE
Three-phase power flow

### ISSUE THREAD

**Issue by dobakhshari** [MATPOWER/matpower#226]
I wonder if MATPOWER is capable of running three-phase power flow by Newton-Raphson method.
I searched for this in the latest manual and found nothing, except for distribution unbalanced power flow.
Can MATPOWER handle the general case of three-phase power flow for either mesh or radial networks?

**Comment by rdzman** [comment]
I just added a new _How To_ guide for 3-phase power flow to the [MATPOWER documentation website](https://matpower.org/documentation/).

Check out [How to Run a Three-Phase Power Flow](https://matpower.org/documentation/howto/three-phase.html).
