### ISSUE TITLE
current status of storage

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#241]
I noticed matpower has one function called addstorage. https://matpower.org/docs/ref/matpower6.0/most/addstorage.html
I am curious if there is any progress of storage. Can they charge and discharge power?
Do they have SOC right now?

**Comment by rdzman** [comment]
MOST handles storage, and yes, it does have SoC.

See the [MOST User's Manual](https://matpower.org/docs/MOST-manual-1.3.pdf) for the details. You may want to start with Section 3.6 for an overview. There are examples in Section 7.2.

**Comment by rdzman** [comment]
Btw, if you have MOST-specific questions, it's best to use the [MOST issue tracker](https://github.com/MATPOWER/most/issues).

**Comment by yanda1234** [comment]
I see. Thanks, Dr. Zimmerman! I like your new tool.
