### ISSUE TITLE
problem while running DCOPF

### ISSUE THREAD

**Issue by yanda1234** [MATPOWER/matpower#245]
Hi Dr. Zimmerman,

While running DCOPF after applying toggle_softlims onto a matpower case this morning, I got error as below. I have never seen this before. Do you know why it appears suddently?

<img width="896" alt="image" src="https://github.com/user-attachments/assets/62ddab09-cd6c-4b6b-adcd-0d3057edd2c0">

Best,
Yanda

**Comment by rdzman** [comment]
Not sure. Are you using the MATPOWER 8.0 release version?

Would you be able to send me what I need to reproduce the error?
