### ISSUE TITLE
have_fcn fails on Octave when fmincon is not present

### ISSUE THREAD

**Issue by eike-f** [MATPOWER/matpower#31]
I have the latest stable version of matpower. I'm not sure it applies to the development version.

In octave when octave-optim is not installed, have_fcn(fmincon) crashes.

`octave:3> test_matpower 
error: value on right hand side of assignment is undefined
error: called from
    have_fcn at line 191 column 26
    test_matpower at line 44 column 1
stopped in .../matpower6.0/have_fcn.m at line 191
191:                     vstr = v.Version;
debug> v
v =

  0x0 struct array containing the fields:

    Name
    Version
    Release
    Date

debug> v.Version
debug> v.Release
debug> v.Date
`
This is because fmincon is not installed
`octave:6> fmincon
warning: the 'fmincon' function belongs to the optim package from Octave Forge
`

after installing it, everything works.

Expected behaviour: have_fcn should output that the function is not available.
Best!
Eike

**Comment by rdzman** [comment]
Thanks for reporting. This was fixed in commit 9d0896e shortly after the release of v. 6.0.
