### ISSUE TITLE
Why the column header is not exactly above the values?

### ISSUE THREAD

**Issue by mfirouzin** [MATPOWER/matpower#32]
![image](https://user-images.githubusercontent.com/36706362/36525910-52bf2c04-17c1-11e8-9e18-d583c0367892.png)
Why the column header is not exactly above the values?

**Comment by rdzman** [comment]
The columns are separated by tabs (not spaces), making it easy to copy/paste them to/from a spreadsheet. Most text editors allow you to set the number of spaces that correspond to a tab. If you increase that number (to around 8 or 12) they will line up.
