### ISSUE TITLE
t_psse..................error: Invalid call to length.

### ISSUE THREAD

**Issue by gshimabuko** [MATPOWER/matpower#42]
I own a notebook running Arch Linux where I am trying to run version 6.0 (latest stable release at this point) on GNU Octave (version 4.4.0).

After adding the paths suggested in the installation guide from the user manual, I ran the code "test_matpower" to which I get the following result:

[..}
t_opf_dc_mips...........ok
t_opf_dc_mips_sc........ok
t_opf_userfcns..........ok
t_opf_softlims..........ok
t_runopf_w_res..........ok
t_dcline................ok
t_get_losses............ok
t_makePTDF..............ok
t_makeLODF..............ok
t_printpf...............ok
t_vdep_load.............ok
t_total_load............ok
t_scale_load............ok
t_apply_changes.........ok
t_psse..................error: Invalid call to length.  Correct usage is:

 -- length (A)
error: called from
    print_usage at line 91 column 5
    psse_parse_line at line 65 column 12
    t_psse at line 61 column 14
    t_run_tests at line 58 column 5
    test_matpower at line 128 column 1

I've searched the archives, and googled it but I was not able to find the cause of the error.
I ran the same test on Matlab, on the same computer and despite some warnings, all tests were successful.

**Comment by rdzman** [comment]
MATPOWER 6 assumed a certain behavior of Octave's `regex` function that subsequently changed in  Octave 4.3 and later. This has been fixed in the current master branch.
