### ISSUE TITLE
Possible typos of matpower manual

### ISSUE THREAD

**Issue by t1393988511** [MATPOWER/matpower#62]
There might be a typo of the matpower manual, at Section 7.2.3, page 81 (lines 2672 and 2678 in MATPOWER-manual.tex).
The functions for adding user-defined linear/nonlinear constraints shall be om.add_lin_constraint/om.add_nln_constraint, instead of om.lin_constraint/om.nln_constraint.

**Comment by rdzman** [comment]
You are correct. Thanks for catching and reporting these typos. They've been fixed.
