### ISSUE TITLE
Large MOST models

### ISSUE THREAD

**Issue by lordleoo** [MATPOWER/matpower#75]
Building a MOST model for 8760 hours (1 year) at one shot took 7 hours on a high performance computer cluster just to build the model, without solving it
If you want to do optimal sizing (long term planning), 7 hours means your optimization might take a year even on a cluster.
I used MATLAB's profiler to see where most of the time goes, and I can see that the main culprets are routines:
1) add_named_set, which itself has different uses, but one of its sub-functions where a lot of time was spent was add_var
2) params_lin_constraint.

I tried investigating both routines to try and make some improvements. I couldn't do anything about 1), however, in params_lin_constraint, I could achieve about 20% time savings by changing line #108
from: At = At + Akt_full;
to: At(:, i1:iN) = At(:, i1:iN) + Akt_full(:, i1:iN); %this line was added by ****; original was the one above and it was very slow for large At

Other options to circumvent the problem of building a large MOST model are:

1) Build the model once and modify certain parameters when you test different candidate solutions
- Disadvantages: 
    * moving around a variable of size 5GB is going to be slow
- Advantages: 
    * You can be confident about all inter-temporal coupling and inter-scenario coupling being done right

2) Build several sub-models (slices) is much faster. for example, building 52 small models, with each model = 1 week, takes 3 minutes
after that, you can connect these models together.
In this case, i'd advise making the sub-models NOT mutually exclusive. 
instead, having 1 overlapping period between each 2 consecutive models helps:
You can force a constraint: Pg(last time period of slice i) = Pg(first time period in slice i+1)
This way, the ramping constraint between each J(t) scenario and each scenario J(t+1)
would be built properly. However, stored-energy level still needs to be corrected manually.

- Disadvantages: 
    * In MOST, the constraint on storedEnergyLevel in storage devices is written like:
    for every time period (t): storage_min <= sum(SoC(1:t)) <= storage_max
    so you need to adjust this constraint for all later slices i>1
    * consolidating the variables in all slices will make adjusting the StoredEnergyLevel constraint a delicate matter
    you can circumvent this obstacle by requiring the terminal-storage at each subslice
    to be at a certain level; but that changes the solution.
    * if you mess up the order of variables in OM, the QP.A, QP.l and QP.u matrices might still be correct and you
    would still get a correct optimal solution. 
    However, most_summary(om) would read the results wrong

- Advantages: 
    * Building time is very short; if coupling slices is done right, building small slices and connecting them is going to be very fast

3) Build several sub-models (slices) is much faster. 
Build slice (1) and solve it, if it is feasible proceed to build slice (2), if not, terminate with penalty proportional to slice number
- Disadvantages: 
    * Serious disadvantage is: the solver may act wasteful or relaxed in earlier slices. 
    finding a feasible solution for later hours may require oversizing the storage
    this isn't a concern if you have very few components and a simple system. 
    for a complex system, with transmission losses, and different storage devices with different 
    characters. The obtained solution is unlikely to be optimal.
    you can circumvent this obstacle by requiring the terminal-storage at the end of each slice
    to be a certain level; but that changes the solution.
    * You still have to manually correct the constraint StoredEnergyLevel

- Advantages: 
    * saves time on building later slices if early slices dont work
--------------------------------
i think i will proceed with option 2.
you can do option 2, save the model and adjust it instead of rebuilding it everytime

Constraitns that involve/incorporate time coupling accross periods 
(not accross wind-scenarios or between k=0 and contingency(k)) are:
'Rrp'
'Rrm'
'mindown'
'minup'
'uvw'
%}

**Comment by rdzman** [comment]
See MATPOWER/most#7.
