### ISSUE TITLE
CPF: Basecase and targetcase identical (runcpf)

### ISSUE THREAD

**Issue by felnix96** [MATPOWER/matpower#8]
Hi everyone! 
I´m new to Github and Matpower, forgive me if this isn´t the right place for bug-reporting...

I found the following: When **basecase and targetcase are identical**, e.g. both is case9, there **should be** an error displaying:
'Base case and target case have identical load and generation'; (Line 384)

I know that the whole concept of cpf is stupid when they are both the same cases but the error should be displayed correctly anyway :D 

The problem: **runcpf never reaches the end, because the 'success' variable, that is needed in line 586 is not initiated.**

In my runcpf-file I initiated success in the beginning with 0. But I don´t yet have the courage to propose the right change myself or maybe I understood sth. the wrong way, who knows? :/

Thank you for your patience with me :)

**Comment by rdzman** [comment]
👍 Thanks, Felix, for reporting this bug. And yes, this is the right place. 😃
