### ISSUE TITLE
Matpower 7 installation error on Matlab 2019a

### ISSUE THREAD

**Issue by nhelaly102** [MATPOWER/matpower#80]
I am facing an error when I try to install Matpower 7 on Matlab 2019a 

the error starts at:
t_opf_fmincon...........Undefined function or variable 'getIpOptions'.

although when I tried installing same package on an older version of Matlab, it was installed successfully.
![Matlab2019aerror](https://user-images.githubusercontent.com/46346203/63433435-26e4a780-c45e-11e9-9d49-4007bc0ea7c9.PNG)

**Comment by rdzman** [comment]
This looks like a MATLAB installation issue. The function it says it can't find is `getIpOptions` which is part of the Optimization Toolbox and is called internally by `fmincon`. I'd try to reinstall MATLAB and see if that resolves the issue.

FYI, the tests all run fine on MATLAB R2019a on my machine.

**Comment by nhelaly102** [comment]
I tried reinstalling the Matlab again including some of the missing toolboxes, and the problem was resolved.
Thanks so much.
