### ISSUE TITLE
AC power flow with multiple refrence buses

### ISSUE THREAD

**Issue by gridxt** [MATPOWER/matpower#81]
As far as I know, MATPOWER ACPF algorithm cannot handle cases with multiple reference buses. However, there are 3 reference buses defined in the case_SyntheticUSA.m file. How come the 'runpf' command for this case still works? I suspect these buses are ignored...

**Comment by rdzman** [comment]
If there are islands in the network, such as in `case_SyntheticUSA.m`, each island needs to have its own reference bus.

On the other hand, multiple reference buses in a fully connected network will cause problems.

**Comment by gridxt** [comment]
Thanks Ray! Quick question: where in the code do you check for islands? I cannot find it...

**Comment by rdzman** [comment]
The power flow and OPF do not check explicitly, it's just that there will likely be numerical issues if you do not have exactly one reference bus per island.

You can use `case_info()` or `find_islands()` to explicitly check for islands.
