### ISSUE TITLE
an error occurs when i try to run the opf for any case 

### ISSUE THREAD

**Issue by YasirYaqoob888** [MATPOWER/matpower#86]
Output argument "MVAbase" (and maybe others) not assigned during call to "runopf".

**Comment by rdzman** [comment]
My guess is that something is wrong with your MATPOWER installation. My suggestion would be to remove all MATPOWER related directories from your MATLAB path, reinstall the latest MATPOWER (from [matpower.org](https://matpower.org/)), taking care to follow the installation instructions. If that does not resolve the problem, please provide me with the details of exactly what command is causing the error and the exact error message.
