### ISSUE TITLE
Matpower coding

### ISSUE THREAD

**Issue by ayubdawar** [MATPOWER/matpower#87]
Hi there, 
hope u all will be ok and good.
i m working in pf for 30 bus system to identify the week bus using L-index. if anyone have code regarding L-index , anyone can help me in this regards
 thank you

**Comment by rdzman** [comment]
I'm not aware of any, but I suggest you try asking on the [MATPOWER Discussion List](https://matpower.org/mailing-lists/), which is a better forum for this sort of question.
