### ISSUE TITLE
Matpower 7 installation error on Matlab 2019a Unrecognized function or variable 'getIpOptions'.

### ISSUE THREAD

**Issue by aliamin12** [MATPOWER/matpower#88]
![image](https://user-images.githubusercontent.com/60442708/73381239-4ad5d000-42bd-11ea-8ba4-6b5633d418ea.png)

Hi there, I keep getting this error whilst trying to install Matpower 7.0. I have reinstalled Matlab as this was advised to a previous user, and that worked for them. However, after reinstalling I still have the same error. 

Please could you look into this for me. 

Thanks

**Comment by rdzman** [comment]
It looks like there is something unexpected about your Optimization Toolbox installation. Can you post the results of the following commands in MATLAB?

```
ver
exist('fmincon')
which fmincon
```

**Comment by aliamin12** [comment]
![image](https://user-images.githubusercontent.com/60442708/73382270-1c58f480-42bf-11ea-987a-415170a09aef.png)

Please see attached.

**Comment by rdzman** [comment]
It looks like the `fmincon.m` file is present, which is how MATPOWER attempts to detect the presence of the Optimization Toolbox. But, for some reason it is not recognized by MATLAB. Do you have a license for it?

**Comment by rdzman** [comment]
You should be able to test for that with ...

```
license('test', 'optimization_toolbox')
```

**Comment by rdzman** [comment]
I'm assuming that will return a true value (since MATPOWER also checks that). So it seems to me there's something wrong with the MATLAB installation, specifically regarding the Optimization Toolbox. What happens if you try to call `fmincon()`?

**Comment by aliamin12** [comment]
![image](https://user-images.githubusercontent.com/60442708/73382611-bcaf1900-42bf-11ea-885e-fd8ad7afc047.png)

Yes, I believe it is, as my friends have managed to download just fine and they use the same institutional license.

**Comment by aliamin12** [comment]
![image](https://user-images.githubusercontent.com/60442708/73382725-fe3fc400-42bf-11ea-976e-e3e7fb19f32e.png)

**Comment by rdzman** [comment]
Can you try the following (an example from `help fmincon`) ...
```
X = fmincon(@(x) 3*sin(x(1))+exp(x(2)),[1;1],[],[],[],[],[0 0])
```

**Comment by rdzman** [comment]
I'm pretty sure this is a MATLAB/Optimization Toolbox installation issue, but please feel free to re-open this issue if it turns out to be related to MATPOWER.
