### ISSUE TITLE
some files in matpower6.0.zip can't be found in matpower-master

### ISSUE THREAD

**Issue by TheKiteRunning** [MATPOWER/matpower#9]
like `yalmip_options`

**Comment by rdzman** [comment]
It is true. The `extras` directory (where `yalmip_options` is located) is not included in the core `matpower` repository. It has been moved to it's own repository at [`matpower-extras`](https://github.com/MATPOWER/matpower-extras). The plan is that these will still be included in future releases of a MATPOWER zip file, but the are going to be managed through a separate GitHub repository.

You simply need to place the contents of the `matpower-extras` repository in a directory named `extras` inside the MATPOWER install directory `<MATPOWER>` and re-run `install_matpower`.

**Comment by TheKiteRunning** [comment]
Thank you for your kindly help.

By the way, a crash occurs when I run install_matpower. I have been racking my brain but still can't find a solution. 

Since the carsh_dump file is not supported to upload, the detail information is pasted below.

------------------------------------------------------------------------
          Access violation detected at Mon May 01 23:40:33 2017
------------------------------------------------------------------------

Configuration:
  Crash Decoding      : Disabled - No sandbox or build area path
  Crash Mode          : continue (default)
  Current Graphics Driver: Unknown hardware 
  Default Encoding    : GBK
  Deployed            : false
  Graphics card 1     : NVIDIA ( 0x10de ) NVIDIA GeForce 610M Version 9.18.13.2702
  Graphics card 2     : Intel Corporation ( 0x8086 ) Intel(R) HD Graphics 4000 Version 10.18.10.3308
  Host Name           : XX
  MATLAB Architecture : win64
  MATLAB Entitlement ID: Unknown
  MATLAB Root         : D:\Program Files\MATLAB\R2016b
  MATLAB Version      : 9.1.0.441655 (R2016b)
  OpenGL              : hardware
  Operating System    : Microsoft Windows 8.1 professional
  Processor ID        : x86 Family 6 Model 58 Stepping 9, GenuineIntel
  Virtual Machine     : Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode
  Window System       : Version 6.3 (Build 9600)

Fault Count: 1


Abnormal termination:
Access violation

Register State (from fault):
  RAX = 0000000000000001  RBX = 000000006a872860
  RCX = 000000018000d250  RDX = 000000009c2902c0
  RSP = 00000000040395a0  RBP = 00000000040396a0
  RSI = 0000000000000001  RDI = 0000000000000000
 
   R8 = 0000000004039688   R9 = 00007ffc49670000
  R10 = 0000000004039688  R11 = 0000000004039688
  R12 = 0000000000000000  R13 = 000000006a872860
  R14 = 0000000180000000  R15 = ffffffffffffffff
 
  RIP = 000000018000d360  EFL = 00010202
 
   CS = 0033   FS = 0053   GS = 002b

Stack Trace (from fault):
[  0] 0x000000018000d360 D:\Program Files\MATLAB\R2016b\bin\win64\libmx.dll+00054112 matrix::detail::noninlined::mx_array_api::mxIsContainer+00001136
[  1] 0x000000018000bcdf D:\Program Files\MATLAB\R2016b\bin\win64\libmx.dll+00048351 intrusive_ptr_release+00000303
[  2] 0x000000000af040e3 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxetypes.dll+00016611 MathWorks::lxe::ParseTypeScheme+00002011
[  3] 0x000000000af08944 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxetypes.dll+00035140 MathWorks::lxe::CreateXvalueOfMxArrayReference+00001444
[  4] 0x0000000008dace6f D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+01560175 boost::serialization::singleton<boost::serialization::void_cast_detail::void_caster_primitive<ir::IrTree,MathWorks::utl::attachment> >::get_instance+00004915
[  5] 0x000000000af0b5c7 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxetypes.dll+00046535 MathWorks::lxe::LXETypeFactory::~LXETypeFactory+00000279
[  6] 0x0000000008d1555a D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00939354 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00850278
[  7] 0x0000000008d16be3 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00945123 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00856047
[  8] 0x0000000008d19d39 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00957753 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00868677
[  9] 0x0000000008d1932f D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00955183 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00866107
[ 10] 0x0000000008d1940d D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00955405 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00866329
[ 11] 0x0000000008d08041 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00884801 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00795725
[ 12] 0x0000000008c89eab D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00368299 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00279223
[ 13] 0x0000000008c89740 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00366400 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00277324
[ 14] 0x0000000008d11b9b D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00924571 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00835495
[ 15] 0x0000000008d11953 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00923987 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00834911
[ 16] 0x0000000008d11979 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00924025 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00834949
[ 17] 0x00000000080846de D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00018142 Mfh_file::dispatch_fh_impl+00000434
[ 18] 0x00000000080844b6 D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00017590 Mfh_file::dispatch_fh+00000062
[ 19] 0x0000000008085827 D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00022567 Mfunction_handle::dispatch+00001015
[ 20] 0x000000000e26adf2 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00175602
[ 21] 0x000000000e2599a3 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00104867
[ 22] 0x000000000e2590ec D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00102636
[ 23] 0x000000000e258791 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00100241
[ 24] 0x000000000e290dbe D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00331198 mcos::plugins::init__pm_init+00015206
[ 25] 0x000000000e2600e5 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00131301
[ 26] 0x00000000076761c5  D:\Program Files\MATLAB\R2016b\bin\win64\mcos.dll+00090565 omDirectCallMethod+00000069
[ 27] 0x000000000ad2485b D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00084059 MathWorks::lxe::IIndexingContext::HasSubsrefForDot+00002743
[ 28] 0x000000000ad25f1c D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00089884 MathWorks::lxe::concatenate+00002460
[ 29] 0x000000000ad223a4 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00074660 MathWorks::lxe::at_rdot_guarantee_id_1+00001028
[ 30] 0x000000000ad223a4 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00074660 MathWorks::lxe::at_rdot_guarantee_id_1+00001028
[ 31] 0x000000000ad29118 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00102680 MathWorks::lxe::at_rparen+00000592
[ 32] 0x000000000ad29022 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00102434 MathWorks::lxe::at_rparen+00000346
[ 33] 0x000000000ad28f58 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00102232 MathWorks::lxe::at_rparen+00000144
[ 34] 0x0000000008dc6cce D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+01666254 boost::serialization::singleton<boost::serialization::void_cast_detail::void_caster_primitive<ir::IrTree,MathWorks::utl::attachment> >::get_instance+00110994
[ 35] 0x0000000008d1728f D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00946831 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00857755
[ 36] 0x0000000008d17b75 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00949109 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00860033
[ 37] 0x0000000008d19151 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00954705 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00865629
[ 38] 0x0000000008d19c95 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00957589 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00868513
[ 39] 0x0000000008d1932f D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00955183 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00866107
[ 40] 0x0000000008d1940d D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00955405 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00866329
[ 41] 0x0000000008d08041 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00884801 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00795725
[ 42] 0x0000000008c89eab D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00368299 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00279223
[ 43] 0x0000000008c89740 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00366400 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00277324
[ 44] 0x0000000008d11b9b D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00924571 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00835495
[ 45] 0x0000000008d11953 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00923987 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00834911
[ 46] 0x0000000008d11979 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00924025 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00834949
[ 47] 0x00000000080846de D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00018142 Mfh_file::dispatch_fh_impl+00000434
[ 48] 0x00000000080844b6 D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00017590 Mfh_file::dispatch_fh+00000062
[ 49] 0x0000000008085827 D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00022567 Mfunction_handle::dispatch+00001015
[ 50] 0x000000000e276761 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00223073
[ 51] 0x000000000e2765a6 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00222630
[ 52] 0x0000000008085b1f D:\Program Files\MATLAB\R2016b\bin\win64\m_dispatcher.dll+00023327 Mfh_MATLAB_fn::dispatch_fh+00000639
[ 53] 0x000000000e25cba5 D:\Program Files\MATLAB\R2016b\bin\win64\mcos_impl.dll+00117669
[ 54] 0x000000000ad14f97 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00020375 MathWorks::lxe::at_paren_pointer_numeric_matrix_colonobj+00003339
[ 55] 0x000000000ad14ad0 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00019152 MathWorks::lxe::at_paren_pointer_numeric_matrix_colonobj+00002116
[ 56] 0x000000000ad230d8 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00078040 MathWorks::lxe::at_rbrace_nargout+00001624
[ 57] 0x000000000ad23014 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00077844 MathWorks::lxe::at_rbrace_nargout+00001428
[ 58] 0x000000000ad17520 D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00029984 MathWorks::lxe::at_rdot_1_mcos+00000484
[ 59] 0x000000000ad1739e D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00029598 MathWorks::lxe::at_rdot_1_mcos+00000098
[ 60] 0x000000000ad1734c D:\Program Files\MATLAB\R2016b\bin\win64\libmwlxeindexing.dll+00029516 MathWorks::lxe::at_rdot_1_mcos+00000016
[ 61] 0x0000000008e25dbc D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+02055612 boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,MathWorks::lxe::MatlabIrTree>::load_object_data+00074892
[ 62] 0x0000000008d087d7 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00886743 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00797667
[ 63] 0x0000000008d074b8 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00881848 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00792772
[ 64] 0x0000000008c89eab D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00368299 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00279223
[ 65] 0x0000000008c89740 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00366400 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00277324
[ 66] 0x0000000008c83f8f D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00343951 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00254875
[ 67] 0x0000000008c83aa1 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00342689 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00253613
[ 68] 0x0000000008c83991 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00342417 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00253341
[ 69] 0x0000000008e103e9 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+01967081 boost::serialization::singleton<boost::archive::detail::oserializer<boost::archive::polymorphic_oarchive,foundation::msg_svc::eventmgr::BaseEvent> >::get_instance+00003353
[ 70] 0x0000000008e10372 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+01966962 boost::serialization::singleton<boost::archive::detail::oserializer<boost::archive::polymorphic_oarchive,foundation::msg_svc::eventmgr::BaseEvent> >::get_instance+00003234
[ 71] 0x0000000008cd2a61 D:\Program Files\MATLAB\R2016b\bin\win64\m_lxe.dll+00666209 boost::serialization::singleton<boost::archive::detail::iserializer<boost::archive::binaryTerm_iarchive,ir::IrTree> >::get_instance+00577133
[ 72] 0x00000000082eb3bd D:\Program Files\MATLAB\R2016b\bin\win64\m_interpreter.dll+00504765 inEvalCmdWithLocalReturn+00000065
[ 73] 0x00000000fb608ced D:\Program Files\MATLAB\R2016b\bin\win64\libmwbridge.dll+00101613 mnGetPrompt+00012957
[ 74] 0x00000000fb609ba3 D:\Program Files\MATLAB\R2016b\bin\win64\libmwbridge.dll+00105379 mnParser+00001091
[ 75] 0x0000000007f86841   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00223297 mcr::runtime::setInterpreterThreadToCurrent+00025585
[ 76] 0x0000000007f857d7   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00219095 mcr::runtime::setInterpreterThreadToCurrent+00021383
[ 77] 0x0000000007f85853   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00219219 mcr::runtime::setInterpreterThreadToCurrent+00021507
[ 78] 0x0000000007f86141   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00221505 mcr::runtime::setInterpreterThreadToCurrent+00023793
[ 79] 0x00000000fd01d347   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00578375 iqm::UserEvalPlugin::pre+00030679
[ 80] 0x00000000fd029e7c   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00630396 iqm::UserEvalPlugin::pre+00082700
[ 81] 0x00000000fd017480   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00554112 iqm::UserEvalPlugin::pre+00006416
[ 82] 0x00000000fd02c99a   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00641434 iqm::UserEvalPlugin::pre+00093738
[ 83] 0x00000000fcff9a37   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00432695 iqm::PackagedTaskPlugin::PackagedTaskPlugin+00000727
[ 84] 0x00000000fcffa08f   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00434319 iqm::PackagedTaskPlugin::execute+00000575
[ 85] 0x00000000fcff9aa9   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00432809 iqm::PackagedTaskPlugin::PackagedTaskPlugin+00000841
[ 86] 0x00000000fcff9f04   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00433924 iqm::PackagedTaskPlugin::execute+00000180
[ 87] 0x00000000fcfd42fa   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00279290 iqm::Iqm::setupIqmFcnPtrs+00071530
[ 88] 0x00000000fcfd41d3   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00278995 iqm::Iqm::setupIqmFcnPtrs+00071235
[ 89] 0x00000000fcfb9e5a   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00171610 iqm::Iqm::deliver+00003274
[ 90] 0x00000000fcfbad2f   D:\Program Files\MATLAB\R2016b\bin\win64\iqm.dll+00175407 iqm::Iqm::deliver+00007071
[ 91] 0x0000000100108173 D:\Program Files\MATLAB\R2016b\bin\win64\libmwservices.dll+01147251 services::system_events::PpeDispatchHook::dispatchOne+00019059
[ 92] 0x000000010010c3a3 D:\Program Files\MATLAB\R2016b\bin\win64\libmwservices.dll+01164195 sysq::addProcessPendingEventsUnitTestHook+00001923
[ 93] 0x000000010010c580 D:\Program Files\MATLAB\R2016b\bin\win64\libmwservices.dll+01164672 sysq::addProcessPendingEventsUnitTestHook+00002400
[ 94] 0x000000010010d685 D:\Program Files\MATLAB\R2016b\bin\win64\libmwservices.dll+01169029 sysq::getCondition+00002917
[ 95] 0x000000010010e4b2 D:\Program Files\MATLAB\R2016b\bin\win64\libmwservices.dll+01172658 svWS_ProcessPendingEvents+00000162
[ 96] 0x0000000007f86b7d   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00224125 mcr::runtime::setInterpreterThreadToCurrent+00026413
[ 97] 0x0000000007f8726a   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00225898 mcr::runtime::setInterpreterThreadToCurrent+00028186
[ 98] 0x0000000007f7e385   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00189317 mcr_process_events+00010293
[ 99] 0x0000000007f802d2   D:\Program Files\MATLAB\R2016b\bin\win64\mcr.dll+00197330 mcr_process_events+00018306
[100] 0x0000000007ecbd0e D:\Program Files\MATLAB\R2016b\bin\win64\MVMLocal.dll+00245006 mvm_server::inproc::LocalFactory::terminate+00070846
[101] 0x00000000fa942cd9   D:\Program Files\MATLAB\R2016b\bin\win64\mvm.dll+01125593 mvm::detail::initLocalMvmHack+00000521
[102] 0x00000000fa9432a5   D:\Program Files\MATLAB\R2016b\bin\win64\mvm.dll+01127077 mvm::detail::SessionImpl::privateSession+00000373
[103] 0x00000000fa9434b1   D:\Program Files\MATLAB\R2016b\bin\win64\mvm.dll+01127601 mvm::detail::SessionImpl::privateSession+00000897
[104] 0x0000000140006fd5 D:\Program Files\MATLAB\R2016b\bin\win64\MATLAB.exe+00028629
[105] 0x0000000140007661 D:\Program Files\MATLAB\R2016b\bin\win64\MATLAB.exe+00030305
[106] 0x00007ffc5b6313d2                   C:\Windows\system32\KERNEL32.DLL+00005074 BaseThreadInitThunk+00000034
[107] 0x00007ffc5d3d54e4                      C:\Windows\SYSTEM32\ntdll.dll+00087268 RtlUserThreadStart+00000052


If this problem is reproducible, please submit a Service Request via:
    http://www.mathworks.com/support/contact_us/

A technical support engineer might contact you with further information.

Thank you for your help.



选择文件 Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP.
 Styling with Markdown is supported
Comment Close and comment

**Comment by rdzman** [comment]
The Matlab crash in `install_matpower` seems like a Matlab bug, but please open a separate issue for that.
