### ISSUE TITLE
Matpower Installation

### ISSUE THREAD

**Issue by bmitrauncc** [MATPOWER/matpower#98]
Hello,

I have MATLAB R2019b, I have added the folders using setpath option, but I get the error Unrecognized function or variable 'test_matpower'

**Comment by rdzman** [comment]
Did you use the `install_matpower` command to set up the paths?

If not, try removing all MATPOWER paths that you have entered manually and then simply run `install_matpower` and follow the prompts. Option 3 is probably the best option for most people.

**Comment by bmitrauncc** [comment]
Yes it did work, thank you so much for this solution.
